name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build Docker image
        run: docker build --no-cache -t stevenbachimont/wow:latest .



      - name: Push Docker image
        run: docker push stevenbachimont/wow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /root/wow
            git pull origin main
            docker-compose pull web  
            docker-compose up -d web  
            docker image prune -f
